export const SUMMARY_TILES = [
  {
    label: 'Total active',
    value: '118',
    sub: 'Programs',
    icon: 'pi-check-circle',
    color: 'green',
  },
  {
    label: 'Total inactive',
    value: '6',
    sub: 'Programs',
    icon: 'pi-times-circle',
    color: 'red',
  },
  {
    label: 'UG programmes',
    value: '45',
    sub: 'Bachelor Level',
    icon: 'pi-book',
    color: 'blue',
  },
  {
    label: 'PG programmes',
    value: '32',
    sub: 'Master Level',
    icon: 'pi-graduation-cap',
    color: 'purple',
  },
  {
    label: 'Diploma / Cert',
    value: '28',
    sub: 'Specialized',
    icon: 'pi-id-card',
    color: 'teal',
  },
  {
    label: 'NEP-based',
    value: '64',
    sub: 'Credit Scheme',
    icon: 'pi-verified',
    color: 'amber',
  },
];

export const SETTINGS_ACTIONS = [
  {
    label: 'Add New Programme',
    icon: 'pi-plus-circle',
    color: 'blue',
    desc: 'Create new programmes',
  },
  {
    label: 'Programme',
    icon: 'pi-list',
    color: 'indigo',
    desc: 'Configured programmes',
  },
  {
    label: 'Courses',
    icon: 'pi-book',
    color: 'teal',
    desc: 'Course management',
  },
  {
    label: 'Academic Distinction',
    icon: 'pi-star',
    color: 'amber',
    desc: 'Degree, Diploma, etc.',
  },
  {
    label: 'Bulk import courses',
    icon: 'pi-upload',
    color: 'cyan',
    desc: 'Upload via Excel',
  },
  {
    label: 'Uploaded Documents',
    icon: 'pi-file-pdf',
    color: 'rose',
    desc: 'Document repository',
  },
  {
    label: 'Programme Re-Registration',
    icon: 'pi-refresh',
    color: 'emerald',
    desc: 'Student management',
  },
  {
    label: 'Advance Settings',
    icon: 'pi-sliders-h',
    color: 'orange',
    desc: 'Hierarchy settings',
    isMega: true,
  },
  {
    label: 'Admission Settings',
    icon: 'pi-user-plus',
    color: 'violet',
    desc: 'Admin configs',
  },
  {
    label: 'Access Control',
    icon: 'pi-key',
    color: 'slate',
    desc: 'Rights & permissions',
  },
];

export const ADVANCE_SUB_ITEMS = [
  'Programme Disciplines',
  'UGC Specified Degree',
  'Admission Quotas',
  'Enrolment Types',
  'Enrolment Status',
  'Exam Schemes',
];

export const PROGRAMMES = [
  {
    id: 1,
    code: 'BSCCS',
    shortCode: 'BSCCS01',
    title: 'B.Sc. Computer Science',
    titleHi: 'बी.एस.सी. कंप्यूटर साइंस',
    ugcDegree: 'B.Sc.',
    type: 'Degree',
    level: 'Bachelor',
    mode: 'Regular',
    examScheme: 'Semester',
    creditScheme: 'Yes (NEP)',
    totalCredits: 120,
    minDuration: '3 Years',
    maxDuration: '5 Years',
    lateralEntry: 'Yes',
    interimExit: 'Yes',
    yearOfStart: 2020,
    status: 'Active',
    orgUnit: 'School of CS & IT',
    seatSnapshot: { sanctioned: 60, general: 30, sc: 9, st: 5, obc: 16 },
    feeRange: 'From ₹15,000 / Sem',
    completeness: {
      orgUnits: true,
      criteria: true,
      docs: true,
      seatFee: true,
      courses: true,
    },
  },
  {
    id: 2,
    code: 'MABIO',
    shortCode: 'MABIO02',
    title: 'M.A. Biotechnology',
    titleHi: 'एम.ए. जैव प्रौद्योगिकी',
    ugcDegree: 'M.A.',
    type: 'Degree',
    level: 'Master',
    mode: 'Regular',
    examScheme: 'Semester',
    creditScheme: 'No',
    totalCredits: 80,
    minDuration: '2 Years',
    maxDuration: '4 Years',
    lateralEntry: 'No',
    interimExit: 'No',
    yearOfStart: 2018,
    status: 'Active',
    orgUnit: 'School of Bioscience',
    seatSnapshot: { sanctioned: 30, general: 15, sc: 4, st: 2, obc: 9 },
    feeRange: 'From ₹25,000 / Sem',
    completeness: {
      orgUnits: true,
      criteria: true,
      docs: false,
      seatFee: true,
      courses: true,
    },
  },
];

export const LEVELS = [
  { label: 'Bachelor', value: 'Bachelor' },
  { label: 'Master', value: 'Master' },
  { label: 'Diploma', value: 'Diploma' },
  { label: 'Doctoral', value: 'Doctoral' },
];
