export const menuConfig: Menu.MenuItem[] = [
  {
    label: 'Core Administrative Services',
    slug: 'core-administrative-services',
    category: 'Administrative',
    icon: 'admin_panel_settings',
    colorScheme: 'blue',
    description: 'Dashboard • Courses • Progress • Finance • Profile',

    children: [
      {
        label: 'User Management',
        slug: 'user-managemnt',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/user-managemnt',
        icon: 'manage_accounts',
        colorScheme: 'blue',
        children: [],
      },
      {
        label: 'Location Management',
        slug: 'location',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/home/sub-menu/location',
        icon: 'explore',
        colorScheme: 'blue',
        children: [
          {
            label: 'State',
            slug: 'state',
            description: 'Manage states and union territories',
            path: '/temp/state',
            icon: 'flag',
            colorScheme: 'blue',
          },
          {
            label: 'Division',
            slug: 'division',
            description: 'Manage divisions',
            path: '/temp/division',
            icon: 'layers',
            colorScheme: 'blue',
          },
          {
            label: 'District',
            slug: 'district',
            description: 'Manage districts',
            path: '/temp/district',
            icon: 'pin_drop',
            colorScheme: 'blue',
          },
          {
            label: 'Tehsil',
            slug: 'tehsil',
            description: 'Manage tehsils',
            path: '/temp/tehsil',
            icon: 'share_location',
            colorScheme: 'blue',
          },
          {
            label: 'Block',
            slug: 'block',
            description: 'Manage blocks',
            path: '/temp/block',
            icon: 'view_module',
            colorScheme: 'blue',
          },
        ],
      },
      {
        label: 'Subject Management',
        slug: 'subject',
        description: 'Manage subject , categories, and more.',
        path: '/home/sub-menu/subject',
        icon: 'menu_book',
        colorScheme: 'purple',
        children: [
          {
            label: 'Mode Of Education',
            slug: 'mode-of-education',
            description: 'Manage Mode of Education',
            path: '/temp/mode-of-education',
            icon: 'model_education',
            colorScheme: 'purple',
          },
          {
            label: 'Subject Category',
            slug: 'subject-category',
            description: 'Manage Subject Category',
            path: '/temp/subject-category',
            icon: 'category',
            colorScheme: 'purple',
          },
          {
            label: 'Subject',
            slug: 'subject',
            description: 'Manage Subject',
            path: '/temp/subject',
            icon: 'menu_book',
            colorScheme: 'purple',
          },
          {
            label: 'Programme Specialization Structure',
            slug: 'programme-specialization-structure',
            description: 'Programme Specialization Structure',
            path: '/temp/programme-specialization-structure',
            icon: 'account_tree',
            colorScheme: 'purple',
          },
        ],
      },

      {
        label: 'Faculty Admin',
        slug: 'faculty-management',
        description: 'Manage office types, departments, and designations.',
        path: '/home/sub-menu/faculty-management',
        icon: 'business',
        colorScheme: 'green',
        children: [
          {
            label: 'Office Type',
            slug: 'office-type',
            description:
              'Manage different types of faculty and administrative offices.',
            path: '/temp/office-type',
            icon: 'business',
            colorScheme: 'green',
          },
          {
            label: 'Department',
            slug: 'department',
            description: 'Manage departments',
            path: '/temp/department',
            icon: 'account_tree',
            colorScheme: 'green',
          },
          {
            label: 'Designation',
            slug: 'designation',
            description: 'Manage designations',
            path: '/temp/designation',
            icon: 'assignment_ind',
            colorScheme: 'green',
          },
          {
            label: 'Faculty',
            slug: 'faculty',
            description: 'Manage faculties',
            path: '/temp/faculty',
            icon: 'groups',
            colorScheme: 'green',
          },
        ],
      },
      {
        label: 'Human Resource',
        slug: 'hr',
        description: 'Manage office types, departments, and designations.',
        path: '/home/sub-menu/hr',
        icon: 'person_search',
        colorScheme: 'orange',
        children: [
          {
            label: 'Caste',
            slug: 'caste',
            description:
              'Manage different types of faculty and administrative offices.',
            path: '/temp/caste',
            icon: 'diversity_3',
            colorScheme: 'orange',
          },
          {
            label: 'Post',
            slug: 'post',
            description: 'Manage posts and positions',
            path: '/temp/post',
            icon: 'work_history',
            colorScheme: 'orange',
          },
          {
            label: 'Religion',
            slug: 'religion',
            description: 'Manage religions',
            path: '/temp/religion',
            icon: 'temple_buddhist',
            colorScheme: 'orange',
          },
          {
            label: 'Qualification',
            slug: 'qualification',
            description: 'Manage qualifications',
            path: '/temp/qualification',
            icon: 'school',
            colorScheme: 'orange',
          },
          {
            label: 'Class',
            slug: 'class',
            description: 'Manage classes',
            path: '/temp/class',
            icon: 'meeting_room',
            colorScheme: 'orange',
          },
          {
            label: 'Section',
            slug: 'section',
            description: 'Manage sections',
            path: '/temp/section',
            icon: 'grid_view',
            colorScheme: 'orange',
          },
          {
            label: 'Designation Type',
            slug: 'designation-type',
            description: 'Manage designation types',
            path: '/temp/designation-type',
            icon: 'label',
            colorScheme: 'orange',
          },
          {
            label: 'Designation',
            slug: 'designation',
            description: 'Manage designations',
            path: '/temp/designation',
            icon: 'assignment_ind',
            colorScheme: 'orange',
          },
        ],
      },
      {
        label: 'College',
        slug: 'college',
        description: 'Manage college types and Categorys.',
        path: '/home/sub-menu/college',
        icon: 'account_balance',
        colorScheme: 'indigo',
        children: [
          {
            label: 'College Type',
            slug: 'college-type',
            description: 'Manage college types',
            path: '/temp/college-type',
            icon: 'business',
            colorScheme: 'indigo',
          },
          {
            label: 'Category',
            slug: 'college-category',
            description: 'Manage college categories',
            path: '/temp/college-category',
            icon: 'category',
            colorScheme: 'indigo',
          },
        ],
      },
      {
        label: 'Other Masters',
        slug: 'other',
        description: 'Manage masters.',
        path: '/home/sub-menu/other',
        icon: 'dataset',
        colorScheme: 'indigo',
        children: [
          {
            label: 'Degree Level',
            slug: 'degree-level',
            description: 'Manage degree levels',
            path: '/temp/degree-level',
            icon: 'signal_cellular_alt',
            colorScheme: 'indigo',
          },
          {
            label: 'Academic Year',
            slug: 'academic-year',
            description: 'Manage academic year records and session details',
            path: '/temp/academic-year',
            icon: 'calendar_month',
            colorScheme: 'indigo',
          },
          {
            label: 'Programme',
            slug: 'programme',
            description: 'Manage programmes',
            path: '/temp/programme',
            icon: 'book_online',
            colorScheme: 'indigo',
          },
          {
            label: 'Specialisation',
            slug: 'specialisation',
            description: 'Manage specialisations',
            path: '/temp/specialisation',
            icon: 'tune',
            colorScheme: 'indigo',
          },
          {
            label: 'Nationality',
            slug: 'nationality',
            description: 'Manage nationalities',
            path: '/temp/nationality',
            icon: 'public',
            colorScheme: 'indigo',
          },
        ],
      },
      {
        label: 'Grant',
        slug: 'grant',
        description: 'Manage grant types and categories.',
        path: '/home/sub-menu/grant',
        icon: 'redeem',
        colorScheme: 'purple',
        children: [
          {
            label: 'Grant Type',
            slug: 'grant-type',
            description: 'Manage grant types',
            path: '/temp/grant-type',
            icon: 'redeem',
            colorScheme: 'purple',
          },
          {
            label: 'Grant Category',
            slug: 'grant-category',
            description: 'Manage grant categories',
            path: '/temp/grant-category',
            icon: 'card_giftcard',
            colorScheme: 'purple',
          },
          {
            label: 'Eligibility Application Process',
            slug: 'eligibility-application-process',
            description: 'Manage eligibility criteria and application process',
            path: '/temp/eligibility-application-process',
            icon: 'fact_check',
            colorScheme: 'purple',
          },
        ],
      },
      {
        label: 'Scheme',
        slug: 'scheme',
        description: 'Manage scheme types and categories.',
        path: '/home/sub-menu/scheme',
        icon: 'receipt_long',
        colorScheme: 'teal',
        children: [
          {
            label: 'Scheme Type',
            slug: 'scheme-type',
            description: 'Manage scheme types',
            path: '/temp/scheme-type',
            icon: 'receipt_long',
            colorScheme: 'teal',
          },
          {
            label: 'Scheme Category',
            slug: 'scheme-category',
            description: 'Manage scheme categories',
            path: '/temp/scheme-category',
            icon: 'folder_special',
            colorScheme: 'teal',
          },
          {
            label: 'Schemes',
            slug: 'schemes',
            description: 'Manage schemes',
            path: '/temp/schemes',
            icon: 'receipt',
            colorScheme: 'teal',
          },
        ],
      },
    ],
  },
  {
    label: 'Employee\nServices',
    slug: 'employee-services',
    category: 'Employee',
    icon: 'badge',
    colorScheme: 'teal',
    description: 'Onboarding • Directory • Settings',
    navigationStyle: 'sidebar',
    children: [
      {
        label: 'Employee Registration',
        slug: 'employee-registration',
        description: 'Quick or full employee onboarding',
        path: '/employee-management',
        icon: 'person_add',
        colorScheme: 'teal',
        children: [],
      },
      {
        label: 'Employee Directory',
        slug: 'employee-directory',
        description: 'View and search all employees',
        path: '/employee-management/directory',
        icon: 'groups',
        colorScheme: 'teal',
        children: [],
      },
      {
        label: 'Settings',
        slug: 'settings',
        description: 'Employee management settings and masters',
        path: '/employee-management/settings',
        icon: 'tune',
        colorScheme: 'teal',
        children: [
          {
            label: 'Nature of Employment',
            slug: 'nature-of-employment',
            description: 'Manage nature of employment master data.',
            path: '/temp/nature-of-employment',
            icon: 'work_history',
            colorScheme: 'teal',
            children: [],
          },
        ],
      },
    ],
  },
  {
    label: 'Academics',
    slug: 'academics',
    category: 'Academics',
    icon: 'auto_stories',
    colorScheme: 'purple',
    description: 'Manage registrar and admin functions',
    navigationStyle: 'sidebar',
    children: [
      {
        label: 'Programme Management',
        slug: 'programme-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/programme-management',
        icon: 'account_tree',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Admission Admin Guide',
        slug: 'admission-admin-guide',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/admission-admin-guide',
        icon: 'how_to_reg',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Academics',
        slug: 'academics',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/academics',
        icon: 'auto_stories',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Evaluation & Grading',
        slug: 'evaluation-&-grading',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/evaluation-&-grading',
        icon: 'fact_check',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Exam Management',
        slug: 'examination-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/examination-management',
        icon: 'quiz',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Certificate Management',
        slug: 'certificate-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/certificate-management',
        icon: 'verified',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Feedback Management',
        slug: 'student-feedback-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/student-feedback-management',
        icon: 'feedback',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Student Additional Information',
        slug: 'student-additional-information',
        description: 'Manage student additional details.',
        path: '/temp/student-additional-information',
        icon: 'person_outline',
        colorScheme: 'purple',
      },
      {
        label: 'Student Application Form',
        slug: 'student-application-form',
        description: 'Create and submit student applications.',
        path: '/temp/student-application-form',
        icon: 'assignment',
        colorScheme: 'purple',
      },
      {
        label: 'Fee Payment Approval (Temp)',
        slug: 'student-fee-approval',
        description: 'Approve student application fee payments.',
        path: '/temp/student-fee-approval',
        icon: 'payments',
        colorScheme: 'purple',
      },
    ],
  },
  {
    label: 'Accounts And Finance',
    slug: 'accounts-and-finance',
    category: 'Finance',
    icon: 'account_balance',
    colorScheme: 'green',
    description: 'Streamline curriculum management and approvals',
    navigationStyle: 'sidebar',
    children: [
      {
        label: 'Financial Supply Chain Management',
        slug: 'financial-supply-chain-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/financial-supply-chain-management',
        icon: 'receipt_long',
        colorScheme: 'green',
        children: [],
      },
    ],
  },
  {
    label: 'Governance',
    slug: 'governance',
    category: 'Governance',
    icon: 'gavel',
    colorScheme: 'indigo',
    description: 'Track student competencies and skill development',
    navigationStyle: 'sidebar',
    children: [
      {
        label: 'Affiliation Management',
        slug: 'affiliation-Management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/affiliation-Management',
        icon: 'account_balance',
        colorScheme: 'indigo',
        children: [],
      },
      {
        label: 'Communication System',
        slug: 'core-communication-system',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/core-communication-system',
        icon: 'forward_to_inbox',
        colorScheme: 'indigo',
        children: [],
      },
      {
        label: 'Grievance Management',
        slug: 'grievance-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/grievance-management',
        icon: 'report',
        colorScheme: 'indigo',
        children: [],
      },
      {
        label: 'Residential Allocation',
        slug: 'residential-allocation-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/residential-allocation-management',
        icon: 'home_pin',
        colorScheme: 'indigo',
        children: [],
      },
      {
        label: 'Hostel Managemnet',
        slug: 'hostel-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/temp/hostel-management',
        icon: 'hotel',
        colorScheme: 'indigo',
        children: [],
      },
    ],
  },
  {
    label: 'Dashboards',
    slug: 'dashboards',
    category: 'Analytics',
    icon: 'dashboard',
    colorScheme: 'amber',
    navigationStyle: 'sidebar',
    description: 'Temporary demo dashboards for all modules',
    children: [
      {
        label: 'CAS Dashboard',
        slug: 'cas-dashboard',
        description:
          'Core Administrative Services overview with KPIs and workflow funnel',
        path: '/cas-dashboard',
        icon: 'admin_panel_settings',
        colorScheme: 'blue',
        children: [],
      },
      {
        label: 'FSCM Dashboard',
        slug: 'fscm-dashboard',
        description:
          'Financial Supply Chain Management with accounts, budget and masters',
        path: '/fscm-dashboard',
        icon: 'account_balance',
        colorScheme: 'green',
        children: [],
      },
      {
        label: 'Core Overview',
        slug: 'core-overview',
        description: 'Central hub for all core administrative functions',
        path: '/core',
        icon: 'grid_view',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Programme Dashboard',
        slug: 'programme-dashboard',
        description: 'Programme management with summary tiles and settings',
        path: '/core/programme-dashboard',
        icon: 'book_online',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Admissions Dashboard',
        slug: 'admissions-dashboard',
        description: 'Admission readiness, fee config and quick metrics',
        path: '/core/admissions-dashboard',
        icon: 'how_to_reg',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Feedback Dashboard',
        slug: 'feedback-dashboard',
        description: 'Student feedback with analytics, timeline and status',
        path: '/core/feedback-dashboard',
        icon: 'feedback',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'E-Housing Dashboard',
        slug: 'ehousing-dashboard',
        description: 'Housing applications, schemes and inventory tracking',
        path: '/core/ehousing-dashboard',
        icon: 'home',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Communication Dashboard',
        slug: 'communication-dashboard',
        description: 'Broadcast history, activity trends and recipient stats',
        path: '/core/communication-dashboard',
        icon: 'forward_to_inbox',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Affiliation Dashboard',
        slug: 'affiliation-dashboard',
        description: 'Affiliation applications, revenue and recent payments',
        path: '/core/affiliation-dashboard',
        icon: 'verified',
        colorScheme: 'purple',
        children: [],
      },
      {
        label: 'Employee Management Dashboard',
        slug: 'employee-management-dashboard',
        description: 'Employee records, department distribution and KPIs',
        path: '/employee-management',
        icon: 'badge',
        colorScheme: 'teal',
        children: [],
      },
      {
        label: 'User Management Dashboard',
        slug: 'user-management-dashboard',
        description: 'User accounts, permissions and activity logs',
        path: '/user-management',
        icon: 'manage_accounts',
        colorScheme: 'indigo',
        children: [],
      },
    ],
  },
  {
    label: 'Get\nInvolved',
    slug: 'get-involved',
    category: 'Campus',
    icon: 'event',
    colorScheme: 'amber',
    description: 'Events • Calendar • Activities',
    children: [
      {
        label: 'View Events',
        slug: 'view-events',
        description: 'Browse campus events and academic calendar',
        path: '/get-involved/view-events',
        icon: 'calendar_month',
        colorScheme: 'amber',
        children: [],
      },
      {
        label: 'Add Event',
        slug: 'add-event',
        description: 'Create a new campus event',
        path: '/get-involved/add-event',
        icon: 'post_add',
        colorScheme: 'amber',
        children: [],
      },
    ],
  },
  // {
  //   label: 'Career\nGateway',
  //   slug: 'career-gateway',
  //   category: 'HR',
  //   icon: 'work',
  //   colorScheme: 'red',
  //   description: 'Career services and job placement resources',
  // },
  // {
  //   label: 'ICON – Research Compliance',
  //   slug: 'icon-research-compliance',
  //   category: 'Academics',
  //   icon: 'science',
  //   colorScheme: 'orange',
  //   description: 'Manage research compliance and ethics approvals',
  // },
  // {
  //   label: 'Disability\nCenter',
  //   slug: 'disability-center',
  //   category: 'HR',
  //   icon: 'accessible',
  //   colorScheme: 'pink',
  //   description: 'Support services for students with disabilities',
  // },
  // {
  //   label: 'Student ID & Campus Allowance',
  //   slug: 'student-id-campus-allowance',
  //   category: 'Finance',
  //   icon: 'credit_card',
  //   colorScheme: 'blue',
  //   description: 'Manage student IDs and campus financial allowances',
  // },
  // {
  //   label: 'University Queue – Virtual Queuing',
  //   slug: 'university-queue-virtual-queuing',
  //   category: 'Operation',
  //   icon: 'desktop_windows',
  //   colorScheme: 'purple',
  //   description: 'Virtual queuing system for campus services',
  // },
  // {
  //   label: 'FIXIT — Facility Management',
  //   slug: 'fixit-facility-management',
  //   category: 'Operation',
  //   icon: 'build',
  //   colorScheme: 'teal',
  //   description: 'Report and manage facility maintenance issues',
  // },
  // {
  //   label: 'Scholarship&\nGrants',
  //   slug: 'scholarship-grants',
  //   category: 'Finance',
  //   icon: 'workspace_premium',
  //   colorScheme: 'indigo',
  //   description: 'Manage scholarship and grant applications',
  // },
];
